name: Java Docker CI-CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Build Jar
      run: mvn clean package

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build Docker Image
      run: docker build -t nagarajanroshen/java-k8s-demo:latest .

    - name: Push Docker Image
      run: docker push nagarajanroshen/java-k8s-demo:latest

    - name: Deploy to Kubernetes
      uses: appleboy/ssh-action@v1
      with:
        host: 172.21.197.249
        username: nagarajan
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          kubectl rollout restart deployment java-demo
